using System.Collections.Generic;

namespace Thawed.Auto
{
    public static class OpcodeExt
    {
        public static string ToName(this Opcode code) => _names[code];
        
        private static readonly Dictionary<Opcode, string> _names = new()
        {
            { Opcode.Aaa, "AAA" },
            { Opcode.Aad, "AAD" },
            { Opcode.Aam, "AAM" },
            { Opcode.Aas, "AAS" },
            { Opcode.Adc, "ADC" },
            { Opcode.Add, "ADD" },
            { Opcode.And, "AND" },
            { Opcode.Bound, "BOUND" },
            { Opcode.Call, "CALL" },
            { Opcode.Cbw, "CBW" },
            { Opcode.Clc, "CLC" },
            { Opcode.Cld, "CLD" },
            { Opcode.Cli, "CLI" },
            { Opcode.Cmc, "CMC" },
            { Opcode.Cmp, "CMP" },
            { Opcode.Cmpsb, "CMPSB" },
            { Opcode.Cmpsw, "CMPSW" },
            { Opcode.Cs, "CS:" },
            { Opcode.Cwd, "CWD" },
            { Opcode.Daa, "DAA" },
            { Opcode.Das, "DAS" },
            { Opcode.Dec, "DEC" },
            { Opcode.Div, "DIV" },
            { Opcode.Ds, "DS:" },
            { Opcode.Enter, "ENTER" },
            { Opcode.Es, "ES:" },
            { Opcode.Hlt, "HLT" },
            { Opcode.Idiv, "IDIV" },
            { Opcode.Imul, "IMUL" },
            { Opcode.In, "IN" },
            { Opcode.Inc, "INC" },
            { Opcode.Insb, "INSB" },
            { Opcode.Insw, "INSW" },
            { Opcode.Int, "INT" },
            { Opcode.Int3, "INT3" },
            { Opcode.Into, "INTO" },
            { Opcode.Iret, "IRET" },
            { Opcode.Ja, "JA" },
            { Opcode.Jb, "JB" },
            { Opcode.Jbe, "JBE" },
            { Opcode.Jcxz, "JCXZ" },
            { Opcode.Jg, "JG" },
            { Opcode.Jge, "JGE" },
            { Opcode.Jl, "JL" },
            { Opcode.Jle, "JLE" },
            { Opcode.Jmp, "JMP" },
            { Opcode.Jnb, "JNB" },
            { Opcode.Jno, "JNO" },
            { Opcode.Jns, "JNS" },
            { Opcode.Jnz, "JNZ" },
            { Opcode.Jo, "JO" },
            { Opcode.Jpe, "JPE" },
            { Opcode.Jpo, "JPO" },
            { Opcode.Js, "JS" },
            { Opcode.Jz, "JZ" },
            { Opcode.Lahf, "LAHF" },
            { Opcode.Lds, "LDS" },
            { Opcode.Lea, "LEA" },
            { Opcode.Leave, "LEAVE" },
            { Opcode.Les, "LES" },
            { Opcode.Lock, "LOCK" },
            { Opcode.Lodsb, "LODSB" },
            { Opcode.Lodsw, "LODSW" },
            { Opcode.Loop, "LOOP" },
            { Opcode.Loopnz, "LOOPNZ" },
            { Opcode.Loopz, "LOOPZ" },
            { Opcode.Mov, "MOV" },
            { Opcode.Movsb, "MOVSB" },
            { Opcode.Movsw, "MOVSW" },
            { Opcode.Mul, "MUL" },
            { Opcode.Neg, "NEG" },
            { Opcode.Nop, "NOP" },
            { Opcode.Not, "NOT" },
            { Opcode.Or, "OR" },
            { Opcode.Out, "OUT" },
            { Opcode.Outsb, "OUTSB" },
            { Opcode.Outsw, "OUTSW" },
            { Opcode.Pop, "POP" },
            { Opcode.Popa, "POPA" },
            { Opcode.Popf, "POPF" },
            { Opcode.Push, "PUSH" },
            { Opcode.Pusha, "PUSHA" },
            { Opcode.Pushf, "PUSHF" },
            { Opcode.Rcl, "RCL" },
            { Opcode.Rcr, "RCR" },
            { Opcode.Repe, "REPE" },
            { Opcode.Repne, "REPNE" },
            { Opcode.Ret, "RET" },
            { Opcode.Retf, "RETF" },
            { Opcode.Rol, "ROL" },
            { Opcode.Ror, "ROR" },
            { Opcode.Sahf, "SAHF" },
            { Opcode.Sar, "SAR" },
            { Opcode.Sbb, "SBB" },
            { Opcode.Scasb, "SCASB" },
            { Opcode.Scasw, "SCASW" },
            { Opcode.Shl, "SHL" },
            { Opcode.Shr, "SHR" },
            { Opcode.Ss, "SS:" },
            { Opcode.Stc, "STC" },
            { Opcode.Std, "STD" },
            { Opcode.Sti, "STI" },
            { Opcode.Stosb, "STOSB" },
            { Opcode.Stosw, "STOSW" },
            { Opcode.Sub, "SUB" },
            { Opcode.Test, "TEST" },
            { Opcode.Wait, "WAIT" },
            { Opcode.Xchg, "XCHG" },
            { Opcode.Xlat, "XLAT" },
            { Opcode.Xor, "XOR" }
        };
    }
}